name: 'Run gradle test'

description: 'Run gradle test for the specified module'

inputs:
  ref:
    description: 'The ref to checkout'
    required: false
    default: ''
  jdk-version:
    description: 'The JDK version to use for the test'
    required: false
    default: '21'

runs;
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    
    - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

    - name: Run test & Make coverage report
      run: |
        ./gradlew clean
        ./gradlew test
        ./gradlew jacocoAllReport
