name: Test

on:
  workflow_call:
    inputs:
      aws-region:
        description: 'The AWS region'
        required: true
        type: string
      aws-role-arn:
        description: 'The AWS role ARN'
        required: true
        type: string

jobs:
  test:
    name: Gradle Test
    runs-on: lomeone-arc-runner-set
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.AWS_REGION }}
          role-to-assume: ${{ inputs.AWS_ROLE_ARN }}

      - name: Gradle test
        uses: lomeone/github-action/gradle/test@main
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          coveralls-token: ${{ secrets.COVERALLS_TOKEN }}
